// hello world actions
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';
// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const DO_LOGOUT = 'DO_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
// questions actions
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_ERROR = 'GET_ALL_QUESTIONS_ERROR';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_ERROR = 'ANSWER_QUESTION_ERROR';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_ERROR = 'CREATE_QUESTION_ERROR';
// Plates actions
export const GET_ALL_PLATES = 'GET_ALL_PLATES';
export const GET_ALL_PLATES_SUCCESS = 'GET_ALL_PLATES_SUCCES';
export const GET_ALL_PLATES_ERROR = 'GET_ALL_PLATES_ERROR';
export const CREATE_PLATE = 'CREATE_PLATE';
export const CREATE_PLATE_SUCCESS = 'CREATE_PLATE_SUCCESS';
export const CREATE_PLATE_ERROR = 'CREATE_PLATE_ERROR';
export const GET_THE_PLATE = 'GET_THE_PLATE';
export const GET_THE_PLATE_SUCCESS = 'GET_THE_PLATE_SUCCESS';
export const GET_THE_PLATE_ERROR = 'GET_THE_PLATE_ERROR';
export const UPDATE_PLATE = 'UPDATE_PLATE';
export const UPDATE_PLATE_ERROR = 'UPDATE_PLATE_ERROR';
export const DELETE_PLATE = 'DELETE_PLATE';
export const DELETE_PLATE_SUCCESS = 'DELETE_PLATE_SUCCESS';
export const DELETE_PLATE_ERROR = 'DELETE_PLATE_ERROR';

// Testimonials actions
export const GET_TESTIMONIAL = 'GET_TESTIMONIAL';
export const GET_TESTIMONIAL_SUCCESS = 'GET_TESTIMONIAL_SUCCES';
export const GET_TESTIMONIAL_ERROR = 'GET_TESTIMONIAL_ERROR';

export const SEND_TESTIMONIAL = 'SEND_TESTIMONIAL';
export const SEND_TESTIMONIAL_SUCCESS = 'SEND_TESTIMONIAL_SUCCES';
export const SEND_TESTIMONIAL_ERROR = 'SEND_TESTIMONIAL_ERROR';

export const UPDATE_TESTIMONIAL = 'UPDATE_TESTIMONIAL';
export const UPDATE_TESTIMONIAL_SUCCESS = 'UPDATE_TESTIMONIAL_SUCCES';
export const UPDATE_TESTIMONIAL_ERROR = 'UPDATE_TESTIMONIAL_ERROR';

export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';
export const DELETE_TESTIMONIAL_SUCCESS = 'DELETE_TESTIMONIAL_SUCCES';
export const DELETE_TESTIMONIAL_ERROR = 'DELETE_TESTIMONIAL_ERROR';
